#!/bin/bash
set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <kibana_version>  (e.g. 9.1.5)"
  exit 1
fi

KBN_VERSION="$1"
PLUGIN_ID="customizableForm"

# Plugin directory (scripts/..)
PLUGIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
KIBANA_JSON="$PLUGIN_DIR/kibana.json"

# Read plugin version from kibana.json
PLUGIN_VERSION=$(grep -oP '"version"\s*:\s*"\K[^"]+' "$KIBANA_JSON")

echo ">>> Building $PLUGIN_ID v$PLUGIN_VERSION for Kibana $KBN_VERSION"

# Backup original kibana.json
BACKUP_FILE="$KIBANA_JSON.bak"

if [ -f "$BACKUP_FILE" ]; then
  echo "!!! Backup file $BACKUP_FILE already exists. Aborting to avoid overwriting."
  exit 1
fi

cp "$KIBANA_JSON" "$BACKUP_FILE"

restore_kibana_json() {
  if [ -f "$BACKUP_FILE" ]; then
    mv "$BACKUP_FILE" "$KIBANA_JSON"
    echo ">>> Restored original kibana.json"
  fi
}

# Ensure restore is called on exit (success or error)
trap restore_kibana_json EXIT

# Patch kibanaVersion only for the build
sed -E -i "s/\"kibanaVersion\": *\"[^\"]+\"/\"kibanaVersion\": \"${KBN_VERSION}\"/" "$KIBANA_JSON"

# Run build from plugin directory
cd "$PLUGIN_DIR"
yarn build --kibana-version "$KBN_VERSION"

# Zip generated by plugin helpers inside plugin build folder
BUILD_ZIP="$PLUGIN_DIR/build/${PLUGIN_ID}-${KBN_VERSION}.zip"

if [ ! -f "$BUILD_ZIP" ]; then
  echo "!!! Build zip not found at $BUILD_ZIP"
  echo ">>> Available files in $PLUGIN_DIR/build:"
  ls -l "$PLUGIN_DIR/build" || true
  exit 1
fi

# Copy to dist with friendly name
DIST_DIR="$PLUGIN_DIR/dist"
mkdir -p "$DIST_DIR"

TARGET_ZIP="$DIST_DIR/${PLUGIN_ID}-${PLUGIN_VERSION}-kibana-${KBN_VERSION}.zip"
cp "$BUILD_ZIP" "$TARGET_ZIP"

echo ">>> Built: $TARGET_ZIP"
